### ISSUE TITLE
Unexpected behavior in multi-word issuer names

### ISSUE THREAD

**Issue by hexadecimalDinosaur** [nukeop/rofi-ykman#2]
When the name of the issuer includes spaces the program does not copy a 2FA code to clipboard but copies everything after the space

For example if the issuer is `multi word` with account `test`, the program will copy `word:test` instead of a 2FA code

**Comment by hexadecimalDinosaur** [comment]
I have found the issue and will be making a fork so I can push a fix

**Comment by nukeop** [comment]
Closed by the way of #3
